{
 "title": "Home energy use (Octopus Energy)",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Total usage over the last year",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT sum(approx_kwh) AS \"Gas (approx)\"\nFROM $table\nWHERE $timeSeries > now() - INTERVAL '1' YEAR",
     "rawQuery": "SELECT sum(approx_kwh) AS \"Gas (approx)\"\nFROM default.octopus_gas_30m\nWHERE (intDiv(toUInt32(start), 1800) * 1800) * 1000 > now() - INTERVAL '1' YEAR",
     "round": "0s",
     "table": "octopus_gas_30m"
    },
    {
     "database": "default",
     "dateTimeColDataType": "start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    sum(kwh) AS Electricity\nFROM $table\nWHERE $timeSeries > now() - INTERVAL '1' YEAR",
     "rawQuery": "SELECT\n    sum(kwh) AS Electricity\nFROM default.octopus_electricity_30m\nWHERE (intDiv(toUInt32(start), 1800) * 1800) * 1000 > now() - INTERVAL '1' YEAR",
     "round": "0s",
     "table": "octopus_electricity_30m"
    }
   ]
  },
  {
   "title": "Average hourly usage over the last year",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT sum(approx_kwh) / (count() / 2) AS \"Gas (approx)\"\nFROM $table\nWHERE $timeSeries > now() - INTERVAL '1' YEAR",
     "rawQuery": "SELECT sum(approx_kwh) / (count() / 2) AS \"Gas (approx)\"\nFROM default.octopus_gas_30m\nWHERE (intDiv(toUInt32(start), 1800) * 1800) * 1000 > now() - INTERVAL '1' YEAR",
     "round": "0s",
     "table": "octopus_gas_30m"
    },
    {
     "database": "default",
     "dateTimeColDataType": "start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT sum(kwh) / (count() / 2) As Electricity\nFROM $table\nWHERE $timeSeries > now() - INTERVAL '1' YEAR",
     "rawQuery": "SELECT sum(kwh) / (count() / 2) As Electricity\nFROM default.octopus_electricity_30m\nWHERE (intDiv(toUInt32(start), 1800) * 1800) * 1000 > now() - INTERVAL '1' YEAR",
     "round": "0s",
     "table": "octopus_electricity_30m"
    }
   ]
  },
  {
   "title": "Gas usage (approx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    approx_kwh\nFROM $table\nWHERE $timeFilter",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(start), 120) * 120) * 1000 as t,\n    approx_kwh\nFROM default.octopus_gas_30m\nWHERE start >= toDateTime(1700448451) AND start <= toDateTime(1700621251)",
     "round": "0s",
     "table": "octopus_gas_30m"
    }
   ]
  },
  {
   "title": "Electricity usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    kwh\nFROM $table\nWHERE $timeFilter",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(start), 600) * 600) * 1000 as t,\n    kwh\nFROM default.octopus_electricity_30m\nWHERE start >= toDateTime(1700016228) AND start <= toDateTime(1700621028)",
     "round": "0s",
     "table": "octopus_electricity_30m"
    }
   ]
  },
  {
   "title": "Combined usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    approx_kwh AS gas_approx_kwh\nFROM $table\nWHERE $timeFilter",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(start), 5) * 5) * 1000 as t,\n    approx_kwh AS gas_approx_kwh\nFROM default.octopus_gas_30m\nWHERE start >= toDateTime(1700364747) AND start <= toDateTime(1700371014)",
     "round": "0s",
     "table": "octopus_gas_30m"
    },
    {
     "database": "default",
     "dateTimeColDataType": "start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    kwh AS electricity_kwh\nFROM $table\nWHERE $timeFilter",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(start), 5) * 5) * 1000 as t,\n    kwh AS electricity_kwh\nFROM default.octopus_electricity_30m\nWHERE start >= toDateTime(1700364747) AND start <= toDateTime(1700371014)",
     "round": "0s",
     "table": "octopus_electricity_30m"
    }
   ]
  },
  {
   "title": "Daily energy usage (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toStartOfInterval(start, INTERVAL '1' DAY) as t,\n    sum(approx_kwh) AS gas_approx_kwh\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    toStartOfInterval(start, INTERVAL '1' DAY) as t,\n    sum(approx_kwh) AS gas_approx_kwh\nFROM default.octopus_gas_30m\nWHERE start >= toDateTime(1700090174) AND start <= toDateTime(1700694974)\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "octopus_gas_30m"
    },
    {
     "database": "default",
     "dateTimeColDataType": "start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toStartOfInterval(start, INTERVAL '1' DAY) as t,\n    sum(kwh) AS electricity_kwh\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    toStartOfInterval(start, INTERVAL '1' DAY) as t,\n    sum(kwh) AS electricity_kwh\nFROM default.octopus_electricity_30m\nWHERE start >= toDateTime(1700090174) AND start <= toDateTime(1700694974)\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "octopus_electricity_30m"
    }
   ]
  },
  {
   "title": "Insertion lag",
   "type": "timeseries",
   "description": "Combination of:\n1) The lag between usage and when Octopus's API exposes new data\n2) The lag between Octopus's API exposing new data and it being imported into ClickHouse",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toStartOfInterval(start, INTERVAL '1' HOUR) AS t,\n    inserted - end AS gas_lag\nFROM $table\nWHERE $timeFilter",
     "rawQuery": "SELECT\n    toStartOfInterval(start, INTERVAL '1' HOUR) AS t,\n    inserted - end AS gas_lag\nFROM default.octopus_gas_30m\nWHERE start >= toDateTime(1698199950) AND start <= toDateTime(1700795550)",
     "round": "0s",
     "table": "octopus_gas_30m"
    },
    {
     "database": "default",
     "dateTimeColDataType": "start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toStartOfInterval(start, INTERVAL '1' HOUR) AS t,\n    inserted - end AS electricity_lag\nFROM $table\nWHERE $timeFilter",
     "rawQuery": "SELECT\n    toStartOfInterval(start, INTERVAL '1' HOUR) AS t,\n    inserted - end AS electricity_lag\nFROM default.octopus_electricity_30m\nWHERE start >= toDateTime(1698199950) AND start <= toDateTime(1700795550)",
     "round": "0s",
     "table": "octopus_electricity_30m"
    }
   ]
  }
 ]
}